BinaryVersion.isCompatible restore binary compatibility (temporarily?)
This commit fixes:
```
$ ./gradlew --stacktrace dist
* What went wrong:
Execution failed for task ':kotlin-stdlib:compileMainJdk7Kotlin'.
> Could not resolve all files for configuration ':kotlin-stdlib:detachedConfiguration3'.
   > Failed to transform main to match attributes {artifactType=classpath-entry-snapshot}.
      > Execution failed for ClasspathEntrySnapshotTransform: /home/bobko/jb/kotlin-tmp/libraries/stdlib/jvm/build/classes/kotlin/main.
         > class org.jetbrains.kotlin.metadata.jvm.deserialization.JvmMetadataVersion overrides final method org.jetbrains.kotlin.metadata.deserialization.BinaryVersion.isCompatible()Z

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':kotlin-stdlib:compileMainJdk7Kotlin'.
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
        at * What went wrong:
Execution failed for task ':kotlin-stdlib:compileMainJdk7Kotlin'.
> Could not resolve all files for configuration ':kotlin-stdlib:detachedConfiguration3'.
   > Failed to transform main to match attributes {artifactType=classpath-entry-snapshot}.
      > Execution failed for ClasspathEntrySnapshotTransform: /home/bobko/jb/kotlin-tmp/libraries/stdlib/jvm/build/classes/kotlin/main.
         > class org.jetbrains.kotlin.metadata.jvm.deserialization.JvmMetadataVersion overrides final method org.jetbrains.kotlin.metadata.deserialization.BinaryVersion.isCompatible()Z

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':kotlin-stdlib:compileMainJdk7Kotlin'.
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        ...
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':kotlin-stdlib:detachedConfiguration3'.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1423)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$3600(DefaultConfiguration.java:152)
        ...
Caused by: org.gradle.api.internal.artifacts.transform.TransformException: Failed to transform main to match attributes {artifactType=classpath-entry-snapshot}.
        at org.gradle.api.internal.artifacts.transform.TransformingAsyncArtifactListener$TransformedArtifact.lambda$visit$2(TransformingAsyncArtifactListener.java:232)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
        ...
Caused by: org.gradle.api.internal.artifacts.transform.TransformException: Execution failed for ClasspathEntrySnapshotTransform: /home/bobko/jb/kotlin-tmp/libraries/stdlib/jvm/build/classes/kotlin/main.
        at org.gradle.api.internal.artifacts.transform.DefaultTransformerInvocationFactory$1.lambda$mapResult$3(DefaultTransformerInvocationFactory.java:160)
        at org.gradle.internal.Try$Failure.mapFailure(Try.java:273)
        ...
Caused by: java.lang.IncompatibleClassChangeError: class org.jetbrains.kotlin.metadata.jvm.deserialization.JvmMetadataVersion overrides final method org.jetbrains.kotlin.metadata.deserialization.BinaryVersion.isCompatible()Z
        at org.jetbrains.kotlin.load.kotlin.header.ReadKotlinClassHeaderAnnotationVisitor.createHeader(ReadKotlinClassHeaderAnnotationVisitor.java:69)
        at org.jetbrains.kotlin.incremental.classpathDiff.KotlinClassHeaderClassVisitor.getKotlinClassHeader(BasicClassInfo.kt:110)
        at org.jetbrains.kotlin.incremental.classpathDiff.BasicClassInfo$Companion.compute(BasicClassInfo.kt:59)
        at org.jetbrains.kotlin.incremental.classpathDiff.ClassFileWithContents$classInfo$2.invoke(ClassFile.kt:38)
        at org.jetbrains.kotlin.incremental.classpathDiff.ClassFileWithContents$classInfo$2.invoke(ClassFile.kt:37)
        ...

==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':kotlin-test:kotlin-test-js:compileKotlin2Js'.
> class org.jetbrains.kotlin.utils.JsMetadataVersion overrides final method org.jetbrains.kotlin.metadata.deserialization.BinaryVersion.isCompatible()Z

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':kotlin-test:kotlin-test-js:compileKotlin2Js'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:145)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
        ...
Caused by: java.lang.IncompatibleClassChangeError: class org.jetbrains.kotlin.utils.JsMetadataVersion overrides final method org.jetbrains.kotlin.metadata.deserialization.BinaryVersion.isCompatible()Z
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at org.jetbrains.kotlin.utils.KotlinJavascriptMetadataUtils.parseMetadata(KotlinJavascriptMetadataUtils.kt:88)
        at org.jetbrains.kotlin.utils.KotlinJavascriptMetadataUtils$loadMetadata$2.invoke(KotlinJavascriptMetadataUtils.kt:72)
        at org.jetbrains.kotlin.utils.KotlinJavascriptMetadataUtils$loadMetadata$2.invoke(KotlinJavascriptMetadataUtils.kt:71)
        at org.jetbrains.kotlin.utils.JsLibraryUtils.traverseArchive(JsLibraryUtils.kt:212)
        ...
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':kotlin-stdlib:detachedConfiguration3'.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1423)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$3600(DefaultConfiguration.java:152)
        ...
Caused by: org.gradle.api.internal.artifacts.transform.TransformException: Failed to transform main to match attributes {artifactType=classpath-entry-snapshot}.
        at org.gradle.api.internal.artifacts.transform.TransformingAsyncArtifactListener$TransformedArtifact.lambda$visit$2(TransformingAsyncArtifactListener.java:232)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
        ...
Caused by: org.gradle.api.internal.artifacts.transform.TransformException: Execution failed for ClasspathEntrySnapshotTransform: /home/bobko/jb/kotlin-tmp/libraries/stdlib/jvm/build/classes/kotlin/main.
        at org.gradle.api.internal.artifacts.transform.DefaultTransformerInvocationFactory$1.lambda$mapResult$3(DefaultTransformerInvocationFactory.java:160)
        at org.gradle.internal.Try$Failure.mapFailure(Try.java:273)
        ...
Caused by: java.lang.IncompatibleClassChangeError: class org.jetbrains.kotlin.metadata.jvm.deserialization.JvmMetadataVersion overrides final method org.jetbrains.kotlin.metadata.deserialization.BinaryVersion.isCompatible()Z
        at org.jetbrains.kotlin.load.kotlin.header.ReadKotlinClassHeaderAnnotationVisitor.createHeader(ReadKotlinClassHeaderAnnotationVisitor.java:69)
        at org.jetbrains.kotlin.incremental.classpathDiff.KotlinClassHeaderClassVisitor.getKotlinClassHeader(BasicClassInfo.kt:110)
        at org.jetbrains.kotlin.incremental.classpathDiff.BasicClassInfo$Companion.compute(BasicClassInfo.kt:59)
        ...
```

The mentioned problem started happening after combination of two
commits:
- 2/4 Refactoring: move KlibMetadataVersion from util-klib-metadata to util-klib
- 89dd28226b700842f592953b012a2314a96cebe4

This error happens because bootstrap version of JvmMetadataVersion +
JsLibraryUtils AND snapshot version of BinaryVersion end up in one
classpath. I presume that they face each other in `buildSrc` classpath
(since this error started happening after `2/4 Refactoring: move
KlibMetadataVersion from util-klib-metadata to util-klib` commit).
Probably it's because `buildSrc` adds a bunch of modules into it's own
classpath
https://github.com/JetBrains/kotlin/blob/master/buildSrc/build.gradle.kts#L111

You can revert this commit after bootstraping (I checked it locally).
But I'm not sure that we should revert it because BinaryVersion is
packed in a bunch of Kotlin jars that are used by users (kotlin-reflect
is the most significant):
```
./org/jetbrains/kotlin/kotlin-klib-commonizer-embeddable/1.8.255-SNAPSHOT/kotlin-klib-commonizer-embeddable-1.8.255-20230118.175723-1.jar:      7221  1980-02-01 00:00   kotlinx/metadata/internal/metadata/deserialization/BinaryVersion.class
./org/jetbrains/kotlin/kotlin-compiler/1.8.255-SNAPSHOT/kotlin-compiler-1.8.255-20230118.175723-1.jar:      7196  1980-02-01 00:00   org/jetbrains/kotlin/metadata/deserialization/BinaryVersion.class
./org/jetbrains/kotlin/jvm-abi-gen/1.8.255-SNAPSHOT/jvm-abi-gen-1.8.255-20230118.175723-1.jar:      6984  1980-02-01 00:00   org/jetbrains/kotlin/jvm/abi/kotlinx/metadata/internal/metadata/deserialization/BinaryVersion.class
./org/jetbrains/kotlin/kotlin-jps-plugin/1.8.255-SNAPSHOT/kotlin-jps-plugin-1.8.255-20230118.175723-1.jar:      7196  1980-02-01 00:00   org/jetbrains/kotlin/metadata/deserialization/BinaryVersion.class
./org/jetbrains/kotlin/kotlin-klib-commonizer/1.8.255-SNAPSHOT/kotlin-klib-commonizer-1.8.255-20230118.175723-1.jar:      7221  1980-02-01 00:00   kotlinx/metadata/internal/metadata/deserialization/BinaryVersion.class
./org/jetbrains/kotlin/kotlin-reflect/1.8.255-SNAPSHOT/kotlin-reflect-1.8.255-20230118.175723-1.jar:      6633  1980-02-01 00:00   kotlin/reflect/jvm/internal/impl/metadata/deserialization/BinaryVersion.class
./org/jetbrains/kotlin/kotlin-compiler-embeddable/1.8.255-SNAPSHOT/kotlin-compiler-embeddable-1.8.255-20230118.175723-1.jar:      7196  1980-02-01 00:00   org/jetbrains/kotlin/metadata/deserialization/BinaryVersion.class
./org/jetbrains/kotlin/jvm-abi-gen-embeddable/1.8.255-SNAPSHOT/jvm-abi-gen-embeddable-1.8.255-20230118.175723-1.jar:      6984  1980-02-01 00:00   org/jetbrains/kotlin/jvm/abi/kotlinx/metadata/internal/metadata/deserialization/BinaryVersion.class
```

and users may face with the same classpath hell problem. So it's
probably better to keep this method `open` for a while